index:
    path: /
    controller: App\Controller\HomeController::index
## config/routes.yaml
#
## load some routes - one should ultimately have the path "/app"
#controllers:
#  resource: ../src/Controller/SecurityController.php
#  type:     annotation
#  prefix:   /
#
## redirecting the homepage
#homepage:
#  path: /
#  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#  defaults:
#    path: /login
#    permanent: true